# /Users/ahmedrezk/.config/tmuxinator/SimplifiedQuotingReactDotnet.yml

name: DEV
root: /Users/ahmedrezk/Work/simplified-quoting/dev/

windows:
  - editor-dev:
      - nvim
      - guard
  - server-dev: cd ui && npm run start
  - test-dev: cd ui && DEBUG_PRINT_LIMIT=10000000 npm run test -- --watchAll
  - git-dev:
