customCommands:
  - key: "C"
    description: Pick AI commit
    command: oco
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal

git:
  paging:
    colorArg: always
    pager: delta --light --paging=never --side-by-side
gui:
  showIcons: true
  theme:
    lightTheme: true
