# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: ollama:qwen2.5-coder:14b
clients:
  - type: openai-compatible
    name: ollama
    api_base: http://192.168.XXXX:11434/v1
    models:
      - name: deepseek-r1
      - name: deepseek-r1:14b
      - name: qwq:32b
      - name: qwen2.5-coder:14b
      - name: qwen2.5-coder:7b
